<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta charset="utf-8" />
<title>Member Report</title>
<meta name="description" content="3 styles with inline editable feature" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

<!-- bootstrap & fontawesome -->
<link rel="stylesheet" href="assets/css/bootstrap.min.css" />
<link rel="stylesheet" href="assets/font-awesome/4.2.0/css/font-awesome.min.css" />

<!-- page specific plugin styles -->
<link rel="stylesheet" href="assets/css/jquery-ui.custom.min.css" />
<link rel="stylesheet" href="assets/css/jquery.gritter.min.css" />
<link rel="stylesheet" href="assets/css/select2.min.css" />
<link rel="stylesheet" href="assets/css/datepicker.min.css" />
<link rel="stylesheet" href="assets/css/bootstrap-editable.min.css" />

<!-- text fonts -->
<link rel="stylesheet" href="assets/fonts/fonts.googleapis.com.css" />

<!-- ace styles -->
<link rel="stylesheet" href="assets/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />
<link rel="stylesheet" href="assets/css/mine.css"   />

<!--[if lte IE 9]>
			<link rel="stylesheet" href="assets/css/ace-part2.min.css" class="ace-main-stylesheet" />
		<![endif]-->

<!--[if lte IE 9]>
		  <link rel="stylesheet" href="assets/css/ace-ie.min.css" />
		<![endif]-->

<!-- inline styles related to this page -->

<!-- ace settings handler -->
<script src="assets/js/ace-extra.min.js"></script>

<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
		<script src="assets/js/html5shiv.min.js"></script>
		<script src="assets/js/respond.min.js"></script>
<![endif]-->
</head>

<body class="no-skin">
<div class="main-container" id="main-container">
 
<div class="main-content">
  <div class="main-content-inner">
    
    <div class="page-content">
      
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td >
      
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td style="padding:10px" width="156"><img src="assets/images/logoPdf.jpg" width="156" alt="Bharosa Club logo"></td>
      <td style="color:#000; font-size:18px; letter-spacing:0.5px; text-align:right; font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif"> 
      Purchase by Statement
</td>
    </tr>
  </tbody>
</table>

      
      </td>
    </tr>
     
    <tr>
      <td><table width="100%" border="1" cellspacing="0" cellpadding="0" style="border-collapse:collapse" bordercolor="#282828">
  <tbody>
    <tr>
      <td  style="padding:10px" width="50%"><strong>ARVIND KAUSHAL</strong><br>
CAN :36263726326326<br>
393 A PKT 2 <br>
PHASE 1<br>
MAYUR VIHAR<br>
DELHI- 110091<br>
<strong>Email Id : ARVIND.KAUSHAL@YAHOO.COM</strong></td>
      <td valign="top" style="padding:10px">Generated on : 24/04/2016 10:30AM<br>
Generated by : Arvind Kaushal<br>
No. of Page : 2</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td><table width="100%" border="1" cellspacing="0" cellpadding="0" style="border-collapse:collapse" bordercolor="#282828">
                <thead>
                  <tr bgcolor="#747474" style="color:white; letter-spacing:0.5px">
                    <th style="padding:5px;">Transaction Date &amp; Time</th>
                    <th style="padding:5px;">Scheme Name</th>
                    <th style="padding:5px;">Purchase Type</th>
                    <th style="padding:5px;">Amount</th>
                    <th style="padding:5px;">Status</th>
                    <th style="padding:5px;">Payment Mode</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td style="padding:5px;">March 15, 2016 5:42 PM</td>
                    <td style="padding:5px;">Test</td>
                    <td style="padding:5px;">Lumpsum</td>
                    <td style="padding:5px;">2000</td>
                    <td style="padding:5px;">pending</td>
                    <td style="padding:5px;">PayEeez</td>
                  </tr>

                  <tr>
                    <td style="padding:5px;">March 15, 2016 5:42 PM</td>
                    <td style="padding:5px;">Test</td>
                    <td style="padding:5px;">Lumpsum</td>
                    <td style="padding:5px;">2000</td>
                    <td style="padding:5px;">pending</td>
                    <td style="padding:5px;">PayEeez</td>
                  </tr>


                  <tr>
                    <td style="padding:5px;">March 15, 2016 5:42 PM</td>
                    <td style="padding:5px;">Test</td>
                    <td style="padding:5px;">Lumpsum</td>
                    <td style="padding:5px;">2000</td>
                    <td style="padding:5px;">pending</td>
                    <td style="padding:5px;">PayEeez</td>
                  </tr>
                   
                </tbody>
              </table></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td align="right" style="font-size:12px"> Page 1 of 2</td>
    </tr>
  </tbody>
</table>

      
      
      
      
       
    </div>
    <!-- /.row --> 
  </div>
  <!-- /.page-content --> 
</div>
 
			});
		</script>
</body>
</html>
